# Generated by Django 3.0.7 on 2021-05-04 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('outlet', models.CharField(default='New', max_length=100)),
                ('zone', models.CharField(default='None', max_length=100)),
                ('coordinates', models.CharField(default='None', max_length=100)),
                ('timings', models.CharField(default='None', max_length=100)),
                ('address', models.TextField(null=True)),
                ('remark', models.CharField(default='None', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
