# Generated by Django 3.0.7 on 2021-05-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='remark',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='leads',
            name='owner',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='leads',
            name='status',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
