# Generated by Django 3.0.7 on 2021-05-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20210518_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='zone',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
