# Generated by Django 3.0.7 on 2021-05-18 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20210518_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.Zone'),
        ),
    ]
